### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by OnFire124** [trickybestia/linux-discord-rich-presence#10]
Soo, i have this "all-in-one.py", what do I do with it now?
When I execute it without doing anything to the file afting inserting the info it won't do it.
Help me.

**Comment by OnFire124** [comment]
Additionally:
I tried doing
```
chmod +xs ./all-in-one-py
cp ./all-in-one.py ~/.config/linux-discord-rich-presencerc
```
and it gives me following error:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), paths: ["/home/engin/.config/linux-discord-rich-presencerc"] }', src/rich_presence_config.rs:89:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by trickybestia** [comment]
> Soo, i have this "all-in-one.py", what do I do with it now?

According to documentation:
> THEY ARE JUST TEMPLATES. To make them work see [configuration guide](https://github.com/trickybestia/linux-discord-rich-presence/blob/main/doc/configuration.md).

Read configuration guide.

> thread 'main' panicked at 'called Result::unwrap() on an Err value: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), paths: ["/home/engin/.config/linux-discord-rich-presencerc"] }', src/rich_presence_config.rs:89:59
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Looks like you either don't have python installed or have it installed under a different name. If you really have python installed, change first line in `~/.config/linux-discord-rich-presencerc` to your actual python path (depends on your distro, many distros use `python3`, not `python`).

**Comment by trickybestia** [comment]
> Perhaps you could put this information as part of documentation for people who aren't big brained.

Looks like a good idea. Changed shebang in python configs to `#!/usr/bin/python3`. Most distros have Python at this path.
