### ISSUE TITLE
Support for partySize & partyMax

### ISSUE THREAD

**Issue by literon36** [trickybestia/linux-discord-rich-presence#12]
Is anything planned regarding support for the partySize / partyMax properties?

**Comment by trickybestia** [comment]
> Is anything planned regarding support for the partySize / partyMax properties?

Didn't know that it can be useful for someone. Will add support for this tomorrow or in a few days.

**Comment by literon36** [comment]
That would be awesome! Thank you!

**Comment by trickybestia** [comment]
Implemented this feature in v3.2.0.

**Comment by literon36** [comment]
![image](https://user-images.githubusercontent.com/125917933/220319435-23e514ce-406c-4181-b747-b127fdca0ac4.png)
haha it works tysm

but just out of interest... what are "additionalProperties" used for? I couldn't find any information on the web 🤔

**Comment by trickybestia** [comment]
> what are "additionalProperties" used for?

`"additionalProperties": false` is used for indicating that object can't have any properties except those defined in "properties".

**Comment by literon36** [comment]
Thanks a lot! Keep up the great work!
