### ISSUE TITLE
Make timestamp show process runtime instead of system uptime

### ISSUE THREAD

**Issue by liif-starstorm** [trickybestia/linux-discord-rich-presence#14]
Hi there,

I'm having a bit of an issue changing the `'start_timestamp'` line so it shows the time the process is running instead of the system uptime. I would like to display a game that's not run via Steam, so system uptime doesn't make sense here.

Also, if possible, I'd like to make it so the time wouldn't reset each time I change the value of `state` or `details`.

I tried searching Google to find a replacement for uptime that I could apply in this situation, but the things I tried didn't exactly work out, probably because I used wrong commands or the wrong syntax. Help would be really appreciated.

The closest I got was with`'start_timestamp': int(cmd('date +%s')),`, but this way the time elapsed shown in Discord resets every ten seconds

Thank you very much in advance! And, btw, thanks for making this, I really love it!

**Comment by trickybestia** [comment]
Hi!
Looks like you are using example Python config. Add these lines after `cmd` and before `update`:
```py
from os import stat

def pidof(process_name):
    cmd_output = cmd("pidof " + process_name)

    if cmd_output == "":  # if there is no process with this name
        raise Exception()

    return cmd_output.split()[0]  # if there are multiple processes with same name return the first PID from pidof command

def process_start_timestamp(process_name):
    return int(stat(f"/proc/{pidof(process_name)}").st_mtime)
```
Now you can write `'start_timestamp': process_start_timestamp("game process name")` and it will work BUT you need to handle the case when the game is not running. You can write something like this (using example config):
```py
def update():
    try:
        start_timestamp = process_start_timestamp("game process name")
    except:
        # the game is not running
        return []  # show no applications

    return [
        {
            "application_id": 000000000000000000,
            "state": cmd(
                "uname -r"
            ),  # Use `cmd('command_to_run')` if you want to run command like in terminal and show it's result, otherwise if you want show text here comment this line and uncomment next:
            # 'state': 'Your text',
            "details": cmd("uname -n"),  # same here
            "large_image": {"key": "some_image", "text": None},
            "small_image": None,
            "start_timestamp": start_timestamp,
            "end_timestamp": None,
            "buttons": [{"label": "some_button", "url": "https://example.com/"}],
            "party": [1, 3],  # 'party': [current party size, max party size],
        }
    ]
```
I hope this will help you.

**Comment by liif-starstorm** [comment]
Thanks a bunch, this works like a charm!
