### ISSUE TITLE
Debian support?

### ISSUE THREAD

**Issue by FormunaGit** [trickybestia/linux-discord-rich-presence#16]
This looks really interesting but it looks like Debian/Ubuntu support hasn't been made yet.
yo, can i join the pixvin
Do you have thoughts about maybe releasing a deb/appimage for us debian derivatives users, or will I have to just compile it?

**Comment by trickybestia** [comment]
I have no plans about releasing .deb or AppImage packages. You can run [installation script from README](https://github.com/trickybestia/linux-discord-rich-presence?tab=readme-ov-file#manually-compile-from-source) on any distribution and it should work.

**Comment by trickybestia** [comment]
You also can check [makedeb](https://github.com/makedeb/makedeb) utility which can create .deb packages from PKGBUILDs. I tried it once for fun and it worked.

**Comment by FormunaGit** [comment]
hello, its been a while, ive installed arch for the sole purpose of using this
