### ISSUE TITLE
Rich presence updated ?

### ISSUE THREAD

**Issue by Captn138** [trickybestia/linux-discord-rich-presence#17]
I noticed a few days ago that the 'buttons' weren't displaying anymore.
As I sew some of my friends still having these kind of buttons on their prefile with an other app doing the RPC, I'm wondering if there has been any update to the RPC API that broke the software.

**Comment by trickybestia** [comment]
Thank you for your report.
Now I tried to add buttons to my config and they really don't work.
I checked [Discord Rich Presence format docs](https://discord.com/developers/docs/rich-presence/how-to) and it looks like they removed ability to add buttons with custom labels. Now there can be only "Ask to join" and "Spectate" buttons dedicated for games. Ability to add URLs to these buttons is removed too.
Do your friends have buttons with labels other than I mentioned?

**Comment by Captn138** [comment]
Thank you for your quick answer.
Yes, my friend has a 'Join server' button that links to one of our Discord servers.

**Comment by trickybestia** [comment]
Interesting, I've made some research and found out that other users see buttons, but person who has this activity does not.
Can you ask your friends if they see buttons in your Discord activity?

**Comment by Captn138** [comment]
Hey,
It's exactly as you said.
I can't see the buttons, but they are still working and my friends can see them.
Thanks for looking into it
