### ISSUE TITLE
Error when running the command

### ISSUE THREAD

**Issue by gaurav-null** [trickybestia/linux-discord-rich-presence#18]
[ERROR] Error while reading config file: `Is a directory (os error 21)`

**Comment by trickybestia** [comment]
Please provide me the following information:
1. What is your Linux distribution?
2. Did you install using AUR helper or manually compiled from source?
3. Do you launch program using .desktop file or from terminal? If from terminal, provide CLI arguments you are using.
4. Provide your config file.

**Comment by trickybestia** [comment]
@gaurav-null has your issue been resolved?
