### ISSUE TITLE
"Error while settomg activity 'Broken pipe (os error 32)'. Retrying after 10 seconds.

### ISSUE THREAD

**Issue by THEHOMAK** [trickybestia/linux-discord-rich-presence#2]
And it goes on and on and on. Any help?
Installed following the manual, Manjaro Linux.

**Comment by trickybestia** [comment]
I have built and installed it using instructions from manual just now, and it's working well with my current config. It looks like your config is broken, so can you provide config that you are using?

**Comment by THEHOMAK** [comment]
> I have built and installed it using instructions from manual just now, and it's working well with my current config. It looks like your config is broken, so can you provide config that you are using?

#!/bin/python

import json
from os import popen
from contextlib import suppress

def cmd(command):
    with popen(command) as process:
        return process.read()[0:-1]

def update():
    return {'update_delay': 10, 'items': [{
        'application_id': 000000000000000000,
        'state': cmd('uname -r'),
        'details': cmd('uname -n'),
        'large_image': {'key': 'some_image', 'text': None},
        'small_image': None,
        'start_timestamp': int(cmd('date -d "$(uptime -s)" +%s')),
        'end_timestamp': None,
        'buttons': [{'label': 'some_button',
                    'url': 'https://example.com/'
                     }],
    }]}

with suppress(EOFError):
    while True:
        if input() == 'update':
            print(json.dumps(update()))
            
I just copy-pasted it, so maybe I need to edit something.

**Comment by trickybestia** [comment]
> I just copy-pasted it, so maybe I need to edit something.

Yes, you need. You should create a new application at [Discord Developer Portal](https://discord.com/developers/applications), upload assets which you want to use in your rich presence status and copy all needed IDs (`application_id` and optionally `large_image` and/or `small_image`) to config.

**Comment by THEHOMAK** [comment]
> 

That solved it, thanks! 
I just have one question: How to make "elapsed" timer go from 0 seconds, and not 18 hours and 47 minutes?

**Comment by THEHOMAK** [comment]
> > I just copy-pasted it, so maybe I need to edit something.
> 
> Yes, you need. You should create a new application at [Discord Developer Portal](https://discord.com/developers/applications), upload assets which you want to use in your rich presence status and copy all needed IDs (`application_id` and optionally `large_image` and/or `small_image`) to config.

Thanks, that helped the issue!

**Comment by sirius-sama** [comment]
@trickybestia I am getting this error. It's working fine for a moment then throwing this error and working fine again. Is there any way to make this stable?

**Comment by sirius-sama** [comment]
> > I have built and installed it using instructions from manual just now, and it's working well with my current config. It looks like your config is broken, so can you provide config that you are using?
> 
> #!/bin/python
> 
> import json from os import popen from contextlib import suppress
> 
> def cmd(command): with popen(command) as process: return process.read()[0:-1]
> 
> def update(): return {'update_delay': 10, 'items': [{ 'application_id': 000000000000000000, 'state': cmd('uname -r'), 'details': cmd('uname -n'), 'large_image': {'key': 'some_image', 'text': None}, 'small_image': None, 'start_timestamp': int(cmd('date -d "$(uptime -s)" +%s')), 'end_timestamp': None, 'buttons': [{'label': 'some_button', 'url': 'https://example.com/' }], }]}
> 
> with suppress(EOFError): while True: if input() == 'update': print(json.dumps(update()))
> 
> I just copy-pasted it, so maybe I need to edit something.

Why you didn't add this part?
`stdout.flush()
sleep(10)`

**Comment by trickybestia** [comment]
@sirius-sama
> Why you didn't add this part? `stdout.flush() sleep(10)`

You look in issue thread which was closed 8 months ago.

> @trickybestia I am getting this error. It's working fine for a moment then throwing this error and working fine again. Is there any way to make this stable?

Can you share your config?

**Comment by sirius-sama** [comment]
@trickybestia 
> You look in issue thread which was closed 8 months ago.

Sorry I noticed after posting that comment.

> Can you share your config?

Yeah sure, here:
```
#!/bin/python

import json
from os import popen
from sys import stdout
from time import sleep

def cmd(command):
    with popen(command) as process:
        return process.read()[0:-1]

# Missing items behave as if they were None
def update():
    return [{
        'application_id': 1005450886002249778,
        'state': cmd('uname -r'),   # Use `cmd('command_to_run')` if you want to run command like in terminal and show it's result, otherwise if you want text here to show remove the cmd and brackets also -r or -n
        'details': cmd('uname -n'), # same here 
        'large_image': {'key': 'arch_linux', 'text': None},
        'small_image': {'key': 'https://cdn.discordapp.com/emojis/701748042579312741.gif', 'text': None},
        'start_timestamp': int(cmd('date -d "$(uptime -s)" +%s')),
        'end_timestamp': None,
        'buttons': [{'label': 'some_button',
                    'url': 'https://example.com/'
                     }],
    }]

while True:
    print(json.dumps(update()))

    stdout.flush()

    sleep(10)
```

path to file:
```/home/.config/linux-discord-rich-presencerc.py```

log of terminal:
```
[username@arch-machine .config]$ linux-discord-rich-presence -c ~/.config/linux-discord-rich-presencerc.py 
23:37:33 [INFO] Connected to Discord!
23:38:03 [WARN] Error while setting activity: `Broken pipe (os error 32)`. Retrying after 10 seconds.
23:38:14 [INFO] Connected to Discord!
23:38:23 [WARN] Error while setting activity: `Broken pipe (os error 32)`. Retrying after 10 seconds.
23:38:34 [INFO] Connected to Discord!
23:39:13 [WARN] Error while setting activity: `Broken pipe (os error 32)`. Retrying after 10 seconds.
23:39:24 [INFO] Connected to Discord!
23:39:34 [WARN] Error while setting activity: `Broken pipe (os error 32)`. Retrying after 10 seconds.
23:39:44 [INFO] Connected to Discord!
23:40:44 [WARN] Error while setting activity: `Broken pipe (os error 32)`. Retrying after 10 seconds.
```

**Comment by trickybestia** [comment]
@sirius-sama have you installed package from AUR or built it from source?

**Comment by sirius-sama** [comment]
> @sirius-sama have you installed package from AUR or built it from source?

from AUR.

**Comment by trickybestia** [comment]
@sirius-sama interesting. Can you attach build log?
Run this:
```sh
git clone https://github.com/trickybestia/linux-discord-rich-presence.git
cd linux-discord-rich-presence
cargo build --release &> BUILD_LOG
```
And attach BUILD_LOG here (either as file or text).
Thanks.

**Comment by sirius-sama** [comment]
@trickybestia 

```
    Updating crates.io index
   Compiling libc v0.2.127
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling syn v1.0.99
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling log v0.4.17
   Compiling serde_derive v1.0.143
   Compiling cfg-if v0.1.10
   Compiling serde v1.0.143
   Compiling memchr v2.5.0
   Compiling serde_json v1.0.83
   Compiling bitflags v1.3.2
   Compiling once_cell v1.13.0
   Compiling os_str_bytes v6.2.0
   Compiling termcolor v1.1.3
   Compiling itoa v1.0.3
   Compiling heck v0.4.0
   Compiling hashbrown v0.12.3
   Compiling ryu v1.0.11
   Compiling same-file v1.0.6
   Compiling lazycell v1.3.0
   Compiling bytes v1.2.1
   Compiling pin-project-lite v0.2.9
   Compiling textwrap v0.15.0
   Compiling strsim v0.10.0
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.7
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling indexmap v1.9.1
   Compiling tokio v1.20.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling clap_lex v0.2.4
   Compiling walkdir v2.3.2
   Compiling net2 v0.2.37
   Compiling iovec v0.1.4
   Compiling time v0.1.44
   Compiling inotify-sys v0.1.5
   Compiling getrandom v0.2.7
   Compiling atty v0.2.14
   Compiling signal-hook-registry v1.4.0
   Compiling filetime v0.2.17
   Compiling mio v0.8.4
   Compiling mio v0.6.23
   Compiling inotify v0.7.1
   Compiling uuid v0.8.2
   Compiling chrono v0.4.20
   Compiling mio-extras v2.0.6
   Compiling simplelog v0.10.2
   Compiling tokio-macros v1.8.0
   Compiling thiserror-impl v1.0.32
   Compiling notify v4.0.17
   Compiling clap_derive v3.2.15
   Compiling thiserror v1.0.32
   Compiling clap v3.2.16
   Compiling discord-rich-presence v0.1.8
   Compiling linux-discord-rich-presence v3.0.0 (/home/username/linux-discord-rich-presence)
    Finished release [optimized] target(s) in 1m 40s
```

**Comment by trickybestia** [comment]
@sirius-sama i have exactly same dependencies versions and I don't experience any problems with your config.
Unfortunately, I couldn't reproduce your bug so I can't help you.
