### ISSUE TITLE
Error: Permission denied 

### ISSUE THREAD

**Issue by kidp2h** [trickybestia/linux-discord-rich-presence#8]
![image](https://user-images.githubusercontent.com/40386174/186120752-91fac6be-6f7a-4140-b020-f73a0bf8b146.png)
My config: 
![image](https://user-images.githubusercontent.com/40386174/186120945-0dcf494c-66c3-4026-9444-122239426a87.png)

**Comment by trickybestia** [comment]
Run it without sudo.

**Comment by trickybestia** [comment]
@kidp2h I added support for plain JSON configs just now, so you can update linux-discord-rich-presence to v3.1.1 (already in AUR) and your config will work.
